### ISSUE TITLE
Formidable.com: Add Google analytics events to _every single button and link_

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/formidable-landers#51] opened 2016-01-12 20:11 UTC
@paulathevalley this is high priority. Talk to me about prioritizing this.
cc @elizagrace

**Comment by paulathevalley** [comment] 2016-01-21 19:36
- [ ] @elizagrace will be providing utm links & their locations

**Comment by paulathevalley** [comment] 2016-02-05 19:03
Duplicate of https://github.com/FormidableLabs/formidable.com/issues/156

**Closed by paulathevalley** 2016-02-05 19:03 UTC
